#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent any
    triggers { pollSCM('* * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20'))
        timestamps()
    }
    stages {
        stage("docker_login") {
            steps {
            echo "=============docker_login=================="
                withCredentials([usernamePassword(credentialsId: 'dockerhub_jguchieperchik', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker login -u $USERNAME -p $PASSWORD
                    """
                }
            }
        }

        stage("create docker image") {
            steps {
                echo " ============== start bulding image =================="
                dir ('docker/toolbox'){
                sh 'docker build -t jguchieperchik/toolbox.latest .'
                }
            }
        }
        stage("docker push") {
            steps {
                echo " ============== start pushing image =================="
                sh '''
                docker push jguchieperchik/toolbox:latest
                '''
            }
        }
    }
}
